name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  initialize:
    uses: ./.github/workflows/initialize.yml

  verify:
    needs: initialize
    uses: ./.github/workflows/verify.yml

  build:
    needs: verify
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml
